# -*- coding: utf-8 -*-
"""lemon_diseases_detection_project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Esa5BqjiB8ZKeZLN28iEHrXVrZ8surTr
"""



pip install ultralytics

from ultralytics import YOLO

!touch data.yaml

model = YOLO("yolov8m.pt")

results = model.train(data="/content/data.yaml",epochs=50)

refer = YOLO("/content/runs/detect/train/weights/best.pt")

refer.predict("/content/drive/MyDrive/Okul Meyve 2.v2i.yolov8/test/images",save=True,save_txt=True)